In [2]:
%load_ext autoreload
%autoreload 2

In [4]:
import sys,os

In [5]:
sys.path.append(os.path.abspath(os.path.join('../scripts')))

In [6]:

root_path = os.path.abspath('..')
if root_path not in sys.path:
    sys.path.insert(0, root_path)
from data_processing import DataProcessing

In [7]:
da = DataProcessing()

In [20]:
da.read_data('../data/raw/credit_risk_dataset.csv')

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [9]:
da.read_data('../data/processed/credit_risk_dataset.csv')

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,3.135494,10.985310,rent,4.820282,personal,d,10.463132,1.625226,1,0.463734,y,1.386294
1,3.091042,9.169623,own,1.791759,education,b,6.908755,0.041636,0,0.095310,n,1.098612
2,3.258097,9.169623,mortgage,0.693147,medical,c,8.612685,0.603032,1,0.451076,n,1.386294
3,3.178054,11.089821,rent,1.609438,medical,c,10.463132,1.368866,1,0.425268,n,1.098612
4,3.218876,10.904138,rent,2.197225,medical,c,10.463132,1.057340,1,0.438255,y,1.609438
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,4.060443,10.878066,mortgage,0.693147,personal,c,8.665786,0.697138,0,0.104360,n,3.433987
32577,4.007333,11.695255,mortgage,1.609438,personal,a,9.777130,-1.142812,0,0.139762,n,2.995732
32578,4.189655,11.238502,rent,1.386294,homeimprovement,b,10.463132,-0.007040,1,0.378436,n,3.367296
32579,4.043051,11.918397,mortgage,1.791759,personal,b,9.615872,0.151968,0,0.095310,n,3.295837
32580,4.204693,10.645449,rent,1.098612,medical,b,8.775858,-0.331546,0,0.139762,n,3.433987